"""add tabela email_history

Revision ID: 0ad8cd4eac41
Revises: c3661a2357fc
Create Date: 2025-08-30 11:11:59.018389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ad8cd4eac41'
down_revision: Union[str, Sequence[str], None] = 'c3661a2357fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_history',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('recipient', sa.String(), nullable=False),
    sa.Column('html_content', sa.TEXT(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'sent_at', name=op.f('pk_email_history')),
    schema='notification_workers_schema'
    )
    op.create_index(op.f('ix_notification_workers_schema_email_history_id'), 'email_history', ['id'], unique=False, schema='notification_workers_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_workers_schema_email_history_id'), table_name='email_history', schema='notification_workers_schema')
    op.drop_table('email_history', schema='notification_workers_schema')
    # ### end Alembic commands ###
