class TemplateServiceBaseException(Exception):
    ...


class TemplateIntegrityError(TemplateServiceBaseException):
    ...

class TemplateNotFound(TemplateServiceBaseException):
    ...

class InvalidDbRecord(TemplateServiceBaseException):
    ...