services:
  postgres_db:
    image: postgres
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Porta do AMQP para as aplicações
      - "15672:15672" # Interface de gerenciamento web
    environment:
      RABBITMQ_DEFAULT_USER: guest # Usuário padrão para desenvolvimento
      RABBITMQ_DEFAULT_PASS: guest # Senha padrão para desenvolvimento

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    volumes:
      - timescaledata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: history_db
    ports:
      - "5433:5432"

  mailpit:
        image: axllent/mailpit
        container_name: mailpit
        restart: unless-stopped
        volumes:
            - mailpitdata:/data
        ports:
            - 8025:8025
            - 1025:1025
        environment:
            MP_MAX_MESSAGES: 5000
            MP_DATABASE: /data/mailpit.db
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL_HOST: postgres_db
      KC_DB_URL_DATABASE: app_db
      KC_DB_USERNAME: app_user
      KC_DB_PASSWORD: app_password
      KC_DB_SCHEMA: keycloak

      command: start-dev
              

volumes:
  pgdata:
  mailpitdata:
  timescaledata: