"""add colunas de contexto p/ templates email

Revision ID: 3dd17e23efb8
Revises: 061abd3fb25a
Create Date: 2025-08-30 18:38:39.125108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dd17e23efb8'
down_revision: Union[str, Sequence[str], None] = '061abd3fb25a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('context_keys_content', sa.JSON(), nullable=True), schema='templates_api_schema')
    op.add_column('templates', sa.Column('context_keys_subject', sa.JSON(), nullable=True), schema='templates_api_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'context_keys_subject', schema='templates_api_schema')
    op.drop_column('templates', 'context_keys_content', schema='templates_api_schema')
    # ### end Alembic commands ###
