"""add tabela templates

Revision ID: 061abd3fb25a
Revises: a2a9f6dc2646
Create Date: 2025-08-28 23:36:00.049454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '061abd3fb25a'
down_revision: Union[str, Sequence[str], None] = 'a2a9f6dc2646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('template_name', sa.String(), nullable=False),
    sa.Column('channel', sa.Enum('SMS', 'EMAIL', 'MOBILE_PUSH', 'WEB_PUSH', 'WEB_SOCKET', name='channel'), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('html_content', sa.TEXT(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('sms_content', sa.String(), nullable=True),
    sa.Column('generic_title_content', sa.String(), nullable=True),
    sa.Column('generic_content', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_templates')),
    schema='templates_api_schema'
    )
    op.create_index(op.f('ix_templates_api_schema_templates_channel'), 'templates', ['channel'], unique=False, schema='templates_api_schema')
    op.create_index(op.f('ix_templates_api_schema_templates_id'), 'templates', ['id'], unique=False, schema='templates_api_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_templates_api_schema_templates_id'), table_name='templates', schema='templates_api_schema')
    op.drop_index(op.f('ix_templates_api_schema_templates_channel'), table_name='templates', schema='templates_api_schema')
    op.drop_table('templates', schema='templates_api_schema')
    op.execute("DROP TYPE IF EXISTS channel;")
    # ### end Alembic commands ###




